### PR TITLE
call T.Log in the same goroutine to avoid data race

### PR DESCRIPTION
**Pull request by joesis**
For https://github.com/getlantern/lantern-internal/issues/4403

### CODE REVIEW

**Comment by joesis** [comment]
Sometimes when running `go test -count 10 -run Concurrent -race` you'll get below panic, which is expected.
```
panic: Log in goroutine after TestConcurrent has completed

goroutine 40 [running]:
testing.(*common).logDepth(0xc000154a20, 0xc0000942d0, 0x2c, 0x3)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:680 +0x67c
testing.(*common).log(...)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:662
testing.(*common).Log(0xc000154a20, 0xc0001987a0, 0x1, 0x1)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:694 +0x78
github.com/getlantern/golog/testlog.(*testLogWriter).run(0xc0001151d0)
	/Users/joesis/workspace/go/src/github.com/getlantern/golog/testlog/testlog.go:58 +0x116
created by github.com/getlantern/golog/testlog.Capture
	/Users/joesis/workspace/go/src/github.com/getlantern/golog/testlog/testlog.go:24 +0x10b
exit status 2
```

The problem this intended to fix is like below
```
==================
WARNING: DATA RACE
Read at 0x00c0000b4043 by goroutine 12:
  testing.(*common).logDepth()
      /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:675 +0x14b
  testing.(*common).log()
      /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:662 +0x77
  testing.(*common).Log()
      /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:694 +0x1d
  github.com/getlantern/golog/testlog.(*testLogWriter).run()
      /Users/joesis/workspace/go/src/github.com/getlantern/golog/testlog/testlog.go:58 +0x115

Previous write at 0x00c0000b4043 by main goroutine:
  testing.tRunner.func1()
      /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:977 +0x467
  testing.tRunner()
      /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:995 +0x20d
  testing.runTests()
      /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:1282 +0x527
  testing.(*M).Run()
      /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:1199 +0x2ff
  github.com/getlantern/golog/testlog.TestMain()
      /Users/joesis/workspace/go/src/github.com/getlantern/golog/testlog/testlog_test.go:23 +0x224
  main.main()
      _testmain.go:44 +0x21b
```

**Comment by oxtoacart** [comment]
I guess when we call the reset function, it should close the logging goroutine, right?

**Comment by oxtoacart** [comment]
> I guess when we call the reset function, it should close the logging goroutine, right?

Oh I see, you took care of that already!

**Comment by oxtoacart** [comment]
I tried changing to code to just log immediately without using a goroutine and the test doesn't reproduce the original issue ...

**Comment by joesis** [comment]
I separated this PR to two commits. When I checkout https://github.com/getlantern/golog/pull/9/commits/9b2c48e2f12c80f2f855d94effb900c06aedae5d and `go test -count 10 -run Concurrent -race` I could reproduce the data race in 1/3 of chance.

**Comment by oxtoacart** [comment]
> I separated this PR to two commits. When I checkout [9b2c48e](https://github.com/getlantern/golog/commit/9b2c48e2f12c80f2f855d94effb900c06aedae5d) which just added the test code and `go test -count 10 -run Concurrent -race` I could reproduce the data race in 1/3 of chance.

Cool. It looks like the race condition only applies if the logging happens after the completion of the test method. If I add a `time.Sleep(250*time.Millisecond)` at the very end of the test method, right after `stop()`, then I can't reproduce the race condition.

So, I think all you need to do is guard against calling `t.Log` after the completion of the test, something like #10.

**Comment by joesis** [comment]
Wondering why I didn't come up with it in the first place 😀 . Merging thanks @oxtoacart !

**Pull request merged**
